logging:
  level:
    # Enabling trace for app specific logging.
    org.springframework: INFO
    org.springframework.ws.soap: TRACE
    org.springframework.web: INFO
    org.springframework.boot: INFO
    org.eclipse: TRACE
    org.springframework.ws.client.MessageTracing.sent: TRACE
    org.springframework.ws.client.MessageTracing.received: DEBUG
    org.springframework.ws.server.MessageTracing: DEBUG


application:
  name: check-address

spring:
  output:
    ansi:
      enabled: always
server:
  port: 8084
  tomcat:
    max-threads: 10